# TCL File Generated by Component Editor 12.1
# Mon May 13 14:32:58 EDT 2013
# DO NOT MODIFY


# 
# de2_vga_text_buffer "de2_vga_text_buffer" v1.0
# null 2013.05.13.14:32:58
# 
# 

# 
# request TCL package from ACDS 11.0
# 
package require -exact sopc 11.0


# 
# module de2_vga_text_buffer
# 
set_module_property NAME de2_vga_text_buffer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME de2_vga_text_buffer
set_module_property TOP_LEVEL_HDL_FILE de2_vga_text_buffer.vhd
set_module_property TOP_LEVEL_HDL_MODULE de2_vga_text_buffer
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property STATIC_TOP_LEVEL_MODULE_NAME de2_vga_text_buffer
set_module_property FIX_110_VIP_PATH false
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# files
# 
add_file de2_vga_text_buffer.vhd {SYNTHESIS SIMULATION}


# 
# file sets
# 

# 
# parameters
# 


# 
# display items
# 


# 
# connection point vga
# 
add_interface vga avalon end
set_interface_property vga addressAlignment DYNAMIC
set_interface_property vga addressUnits WORDS
set_interface_property vga associatedClock clock_sink
set_interface_property vga associatedReset reset_sink
set_interface_property vga burstOnBurstBoundariesOnly false
set_interface_property vga explicitAddressSpan 0
set_interface_property vga holdTime 0
set_interface_property vga isMemoryDevice false
set_interface_property vga isNonVolatileStorage false
set_interface_property vga linewrapBursts false
set_interface_property vga maximumPendingReadTransactions 0
set_interface_property vga printableDevice false
set_interface_property vga readLatency 0
set_interface_property vga readWaitTime 1
set_interface_property vga setupTime 0
set_interface_property vga timingUnits Cycles
set_interface_property vga writeWaitTime 0
set_interface_property vga ENABLED true

add_interface_port vga vga_read read Input 1
add_interface_port vga vga_write write Input 1
add_interface_port vga vga_chipselect chipselect Input 1
add_interface_port vga vga_address address Input 11
add_interface_port vga vga_readdata readdata Output 32
add_interface_port vga vga_writedata writedata Input 32
set_interface_assignment vga embeddedsw.configuration.isFlash 0
set_interface_assignment vga embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment vga embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment vga embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true

add_interface_port clock_sink vga_clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true

add_interface_port reset_sink vga_reset reset Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock ""
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true

add_interface_port conduit_end display_pixel_on export Output 1

